services:
  api:
    build: .
    image: elevenlabs-ai:dev
    container_name: elevenlabs-ai-api-dev
    ports:
      - "8101:8000"
    env_file:
      - .env
    volumes:
      - .:/app
    restart: unless-stopped
