services:
  api:
    build:
      context: ..
      dockerfile: deploy/Dockerfile
    image: elevenlabs-ai:prod
    container_name: elevenlabs-ai-api
    ports:
      - "8101:8000"
    env_file:
      - .env
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 10s
      timeout: 3s
      retries: 5
