name: Deploy to Amazon EC2

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

env:
  PROJECT_NAME: elevenlabs-ai

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    environment: production

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Deploy via SSH
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USERNAME }}
        key: ${{ secrets.EC2_PRIVATE_KEY }}
        port: 22
        script: |
          cd /home/ubuntu || exit 1
          if [ ! -d "${PROJECT_NAME}/.git" ]; then
            echo "📥 Cloning repository..."
            rm -rf ${PROJECT_NAME}
            git clone https://github.com/johnPa02/elevenlabs-ai.git ${PROJECT_NAME}
          fi

          cd ${PROJECT_NAME}
          git fetch origin
          git checkout main
          git pull origin main

          mkdir -p deploy
          echo "${{ secrets.ENV_FILE }}" > deploy/.env

          docker compose -f deploy/docker-compose.yml down || true

          docker compose -f deploy/docker-compose.yml up -d --build

          echo "✅ Deployed successfully to EC2"
