name: Deploy to Amazon EC2

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

env:
  PROJECT_NAME: elevenlabs-ai

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    environment: production

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Deploy via SSH
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USERNAME }}
        key: ${{ secrets.EC2_PRIVATE_KEY }}
        port: 22
        script: |
          cd /home/ubuntu/${PROJECT_NAME} || https://github.com/johnPa02/elevenlabs-ai.git
          cd ${PROJECT_NAME}
          git fetch origin
          git checkout main
          git pull origin main

          # Write file .env from GitHub Secrets
          echo "${{ secrets.ENV_FILE }}" > deploy/.env

          # Stop old containers
          docker compose -f deploy/docker-compose.yml down || true

          # Build & start new containers
          docker compose -f deploy/docker-compose.yml up -d --build

          echo "✅ Deployed successfully to EC2"
